after_script: 
  - "wget https://scrutinizer-ci.com/ocular.phar"
  - "php ocular.phar code-coverage:upload --format=php-clover coverage.clover"
before_script: 
  - "curl -L https://github.com/kr/beanstalkd/archive/v1.10.tar.gz | tar xz -C /tmp"
  - "cd /tmp/beanstalkd-1.10/"
  - make
  - "./beanstalkd &"
  - "cd $TRAVIS_BUILD_DIR"
install: 
  - "composer self-update --stable"
  - "composer global require \"fxp/composer-asset-plugin:~1.1.1\""
  - "COMPOSER_ROOT_VERSION=dev-master composer install"
language: php
php: 
  - '5.5'
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'
  - '7.3'
  - '7.4'
script: 
  - "vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover"
